language: c
sudo: false
os: linux

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - libgettextpo-dev
      - libqrencode-dev
      - libcrack2-dev
      - libldap2-dev
      - libidn11-dev
      - libpcre3-dev
      - libperl-dev
      - libssl-dev
      - nettle-dev
      - clang-5.0
      - gcc-5

compiler:
  - clang-5.0
  - gcc-5

env:
  - OPTIONAL_CONF_ARGS=""
  - OPTIONAL_CONF_ARGS="--enable-contrib"

script:
  - scripts/travis-build.sh

matrix:
  allow_failures:
    - env: OPTIONAL_CONF_ARGS="--enable-contrib"
