language: c
sudo: false
os: linux
dist: xenial

notifications:
  email: false

addons:
  apt:
    packages:
      - libgettextpo-dev
      - libqrencode-dev
      - libcrack2-dev
      - libidn11-dev
      - libldap2-dev
      - libpcre3-dev
      - libperl-dev
      - libssl-dev
      - nettle-dev
      - clang
      - gcc

compiler:
  - clang-7
  - gcc-5

env:
  - OPTIONAL_CONF_ARGS=""
  - OPTIONAL_CONF_ARGS="--enable-contrib"

script:
  - scripts/travis-build.sh

matrix:
  allow_failures:
    - env: OPTIONAL_CONF_ARGS="--enable-contrib"
