language: c
sudo: false
os: linux

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - libgettextpo-dev
      - libcrack2-dev
      - libidn11-dev
      - libperl-dev
      - libssl-dev
      - nettle-dev
      - clang-5.0
      - gcc-5

compiler:
  - clang-5.0
  - gcc-5

env:
  - OPTIONAL_CONF_ARGS=""
  - OPTIONAL_CONF_ARGS="--with-perl"
  - OPTIONAL_CONF_ARGS="--enable-contrib"

script:
  - ./configure --prefix=/home/travis/atheme-install/ --enable-nls --with-openssl --with-nettle --with-libidn --with-cracklib ${OPTIONAL_CONF_ARGS}
  - make -j $(nproc)
  - make install
  - /home/travis/atheme-install/bin/atheme-services -d -T

matrix:
  allow_failures:
    - env: OPTIONAL_CONF_ARGS="--enable-contrib"
